name: LILA SWANEPOEL PRODUCTIONS
favicon: null
layout_spectrum: 0.3932226216420531
typography_spectrum: 0.32081571547314525
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffedd'
    - '#022845'
    - '#000526'
    - '#085269'
    - '#76a096'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
