name: LILA SWANEPOEL PRODUCTIONS
favicon: null
layout_spectrum: 1
typography_spectrum: 0.53452
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d0e5f1'
    - '#599cc2'
    - '#21242d'
    - '#2c4d6e'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
