analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.48573
title: LILA SWANEPOEL PRODUCTIONS
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 1
  brandStrength: 0
  rhythmicContrast: 0.5
  brandColors:
    - '#000000'
    - '#d0e5f1'
    - '#599cc2'
    - '#21242d'
    - '#2c4d6e'
  lightness: 1
purpose: []
favicon: null
name: LILA SWANEPOEL PRODUCTIONS
typography_spectrum: 0.23365
